#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

case "$1" in
  help | dockerfile:help)
    help_content_func() {
      #shellcheck disable=SC2034
      declare desc="return help_content string"

      cat<<help_content
    dockerfile:set <app> <path/to/Dockerfile>, Set custom path to Dockerfile
    dockerfile:unset <app> <path/to/Dockerfile>, Unset custom path to Dockerfile
help_content
    }

    if [[ $1 = "dockerfile:help" ]]; then
      echo -e 'Usage: dokku dockerfile[:COMMAND] [<app>] [<path>]'
      echo ''
      echo 'Allows to deploy applications with Dockerfiles not residing in the root directory'
      echo ''
      echo 'Additional commands:'
      help_content_func | sort | column -c2 -t -s,
    else
      cat<<help_desc
    dockerfile, Plugin to manage alternative Dockerfile paths
help_desc
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
