#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
APP="$1"; verify_app_name "$APP"
TMP_WORK_DIR="$2"

if [[ -e "$DOKKU_ROOT/$APP/DOCKERFILE_PATH" ]]; then
  pushd "$TMP_WORK_DIR" > /dev/null
  cp $(cat "$DOKKU_ROOT/$APP/DOCKERFILE_PATH") Dockerfile
fi
