#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
APP="$1"; verify_app_name "$APP"
TMP_WORK_DIR="$2"

if [[ -e "$DOKKU_ROOT/$APP/DOCKERFILE_PATH" ]]; then
  pushd "$TMP_WORK_DIR" > /dev/null

  if [[ ! -e $(cat "$DOKKU_ROOT/$APP/DOCKERFILE_PATH") ]]; then
    dokku_log_fail "Dockerfile was not found in specified relative path"
  fi
  cp $(cat "$DOKKU_ROOT/$APP/DOCKERFILE_PATH") Dockerfile
fi
