#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

dockerfile_path_unset_cmd() {
  #shellcheck disable=SC2034
  declare desc="Set relative path to Dockerfile"
  local cmd="dockerfile:unset"
  # Support --app/$DOKKU_APP_NAME flag
  # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@
  ##

  APP="$1"
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"

  [[ -z "$2" ]] && dokku_log_fail "Please specify the relative path to the Dockerfile used in the app $APP"

  if [[ ! -e "$DOKKU_ROOT/$APP/$DOCKERFILE_PATH" ]]; then
          dokku_log_warn "No custom Dockerfile path was set for app $APP"
  else
      rm -rf "$DOKKU_ROOT/$APP/$DOCKERFILE_PATH"
      dokku_log_info1 "Unset custom Dockerfile path for app $APP"
  fi
}

dockerfile_path_unset_cmd "$@"
